FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["HavillahWebUI_MVC/HavillahWebUI_MVC.csproj", "HavillahWebUI_MVC/"]
RUN dotnet restore "HavillahWebUI_MVC/HavillahWebUI_MVC.csproj"
COPY . .
WORKDIR "/src/HavillahWebUI_MVC"
RUN dotnet build "HavillahWebUI_MVC.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "HavillahWebUI_MVC.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "HavillahWebUI_MVC.dll"]
